# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6870820444c671e6b5c4278bcaefc163806fc3f20a931b6c7d6fee1674588026708cc1bf9446a12a5c9d5b7fddad4e90d8578b01be142486393fbf99c60443

test:
  secret_key_base: c79931b9dbde5b33cf09cc67b1de19d54bfd29a8b1fcb7ba9de41f91f32b169144b884df1810a0830e38efdf82f8ede9536875db1190973bac7cd0d09e7b1122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
